project_id = "kovlbxzqasqhigygfiyj"

[functions.setup-demo-users]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.ai-seo-suggestions-multi]
verify_jwt = true